sonar.projectKey=datasluice
sonar.projectName=datasluice
sonar.sources=src
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/*.pem,**/*.env
