"""DataSluice — one Python interface for open-data discovery, extraction,
format normalization, and pipeline integration.
"""

from datasluice._version import __version__
from datasluice.application import (
    DataSluice,
    DirectResourceLocator,
    OpenedResource,
    resource_locator_from_dict,
)
from datasluice.domain import (
    Artifact,
    ArtifactProvenance,
    CatalogCapabilities,
    CredentialScope,
    Dataset,
    DetectionResult,
    Digest,
    HttpDownload,
    License,
    LocalFile,
    ObjectStorage,
    Organization,
    Query,
    QueryAccess,
    Resource,
    ResourceAccess,
    Schema,
    SearchResult,
    StreamAccess,
    SyncState,
)
from datasluice.exceptions import (
    AdapterError,
    AdapterNotFoundError,
    AuthenticationError,
    ChecksumMismatchError,
    ConfigError,
    DataSluiceError,
    DownloadError,
    FormatError,
    NotFoundError,
    OpenedResourceConsumedError,
    PortalDetectionError,
    PortalError,
    RateLimitError,
    ResourceResolutionError,
    StateStoreError,
    SyncStateConflictError,
)

__all__ = [
    "__version__",
    "DataSluice",
    "OpenedResource",
    "DirectResourceLocator",
    "resource_locator_from_dict",
    # Domain models
    "Dataset",
    "Resource",
    "Organization",
    "License",
    "Query",
    "SearchResult",
    "Artifact",
    "ArtifactProvenance",
    "CatalogCapabilities",
    "CredentialScope",
    "DetectionResult",
    "Digest",
    "HttpDownload",
    "LocalFile",
    "ObjectStorage",
    "QueryAccess",
    "ResourceAccess",
    "Schema",
    "StreamAccess",
    "SyncState",
    # Exceptions
    "DataSluiceError",
    "PortalError",
    "AdapterError",
    "AdapterNotFoundError",
    "PortalDetectionError",
    "AuthenticationError",
    "RateLimitError",
    "StateStoreError",
    "SyncStateConflictError",
    "NotFoundError",
    "DownloadError",
    "ChecksumMismatchError",
    "FormatError",
    "ConfigError",
    "ResourceResolutionError",
    "OpenedResourceConsumedError",
]
