"""One-shot destructive-evidence capture driver for the controlled CKAN stack.

Manual runs only (D-10): this driver performs REAL destructive mutations
(dataset/organization/group purges, per-tier forbidden captures, and a bulk
create+delete run) against the loopback-bound evidence stack defined in
dev/ckan-evidence, writing the D-20/D-25 artifacts a later step folds into the
versioned fixture corpus. Credentials are read exclusively from the 0600 JSON
file generated by bootstrap_identities.sh: tokens are never accepted as
command-line arguments and never printed, logged, or written to artifacts.
"""

from __future__ import annotations

import argparse
import json
import stat
import subprocess
from collections.abc import Callable, Sequence
from contextlib import ExitStack
from pathlib import Path
from time import monotonic

from datasluice.connectors.catalog.ckan.clients import SyncCKANClient, create_sync_client
from datasluice.connectors.catalog.ckan.settings import CKANClientSettings
from datasluice.domain.catalog.auth import CKANCredential
from datasluice.domain.catalog.ids import CatalogId, CatalogPlatform, ResourceKind
from datasluice.domain.catalog.models import MappingRecord
from datasluice.domain.catalog.receipts import BulkCheckpoint, BulkPlan, MutationReceipt
from datasluice.domain.catalog.safety import (
    BulkExecutionPolicy,
    ConcurrencyPolicy,
    ConfirmationPolicy,
    MutationPolicy,
)
from datasluice.errors.catalog import ForbiddenError
from datasluice.runtime.bulk import BulkExecutor, BulkItemReceipt, BulkSummary

CREDENTIAL_ROLES = ("sysadmin", "org_admin", "user")
IDENTITIES = ("datasluice-sysadmin", "datasluice-org-admin", "datasluice-user")
EVIDENCE_IMAGES = ("ckan/ckan-base:2.11.5", "ckan/ckan-solr:2.11-solr9", "postgres:17", "redis:8")
EVIDENCE_ORG = "datasluice-evidence-org"
SCRATCH_DATASET = "datasluice-capture-scratch-dataset"
SCRATCH_ORG = "datasluice-capture-scratch-org"
SCRATCH_GROUP = "datasluice-capture-scratch-group"
ORG_ADMIN_DATASET = "datasluice-capture-org-admin"
USER_ORG = "datasluice-capture-user-org"
BULK_PREFIX = "datasluice-capture-bulk"
BULK_OPERATION = "ckan/action-api-v3.dataset-create-update-patch-delete-purge"


def build_parser() -> argparse.ArgumentParser:
    """Build the four-flag CLI surface carrying no token option."""
    parser = argparse.ArgumentParser(
        add_help=False,
        description=(
            "Capture D-20/D-25 destructive and bulk evidence from the loopback CKAN evidence "
            "stack. Credentials are read only from the 0600 JSON file written by "
            "bootstrap_identities.sh."
        ),
    )
    parser.add_argument("-h", action="help", help="show this help message and exit")
    parser.add_argument(
        "--origin", required=True, help="loopback origin of the evidence stack, e.g. http://127.0.0.1:5500"
    )
    parser.add_argument(
        "--credentials-file",
        required=True,
        help="path to the 0600 credentials JSON generated by bootstrap_identities.sh",
    )
    parser.add_argument("--bulk-count", type=int, default=5, help="number of datasets in the bulk create+delete run")
    parser.add_argument("--out-dir", required=True, help="directory receiving the receipt and bulk artifacts")
    return parser


def load_credentials(path: Path) -> dict[str, CKANCredential]:
    """Load the owner-only credentials file into typed per-role credentials.

    Args:
        path: The credentials JSON written by bootstrap_identities.sh.

    Returns:
        One ``CKANCredential`` per seeded role (sysadmin, org_admin, user).

    Raises:
        SystemExit: When the file is missing, group- or world-accessible, or malformed.
    """
    if not path.is_file():
        raise SystemExit(f"credentials file not found: {path}")
    if stat.S_IMODE(path.stat().st_mode) & 0o077:
        raise SystemExit(f"credentials file must be owner-only (0600): {path}")
    try:
        document = json.loads(path.read_text(encoding="utf-8"))
    except ValueError as error:
        raise SystemExit(f"credentials file is not valid JSON: {path}") from error
    tokens = document.get("tokens") if isinstance(document, dict) else None
    string_tokens = (
        {key: value for key, value in tokens.items() if isinstance(key, str)} if isinstance(tokens, dict) else {}
    )
    if not set(CREDENTIAL_ROLES) <= set(string_tokens):
        raise SystemExit(f"credentials file must carry tokens for the roles {CREDENTIAL_ROLES}: {path}")
    if any(not isinstance(string_tokens[role], str) or not string_tokens[role] for role in CREDENTIAL_ROLES):
        raise SystemExit(f"credentials tokens must be non-empty strings: {path}")
    return {role: CKANCredential(api_token=string_tokens[role]) for role in CREDENTIAL_ROLES}


def recorded_origin(path: Path) -> str | None:
    """Return the origin recorded in the credentials file without exposing tokens.

    Args:
        path: The credentials JSON written by bootstrap_identities.sh.

    Returns:
        The recorded origin string, or ``None`` when the file records none.

    Raises:
        SystemExit: When the file is unreadable or the origin is not a string.
    """
    try:
        document = json.loads(path.read_text(encoding="utf-8"))
    except OSError as error:
        raise SystemExit(f"credentials file is unreadable: {path}") from error
    origin = document.get("origin") if isinstance(document, dict) else None
    if origin is not None and not isinstance(origin, str):
        raise SystemExit(f"credentials file origin must be a string: {path}")
    return origin


def build_capture_settings(origin: str, credential: CKANCredential) -> CKANClientSettings:
    """Construct settings whose probe policy makes the loopback posture explicit.

    The controlled stack runs on a plain-http loopback origin, so the auto
    policy's HTTPS-scoped default probe runners stay out of the picture and the
    declared-baseline policy documents that choice at the settings seam
    (Pitfall 4 resolution; the HTTPS evidence validator itself stays untouched).

    Args:
        origin: The loopback origin of the evidence stack.
        credential: The per-role token credential for the constructed client.

    Returns:
        Immutable client settings pinned to the declared-baseline probe policy.
    """
    return CKANClientSettings(base_url=origin, credential=credential, probe_policy="declared-baseline")


def _docker_image_digest(reference: str) -> dict[str, str]:
    """Resolve one image reference to its repo digest, degrading when docker is unavailable."""
    try:
        completed = subprocess.run(
            ["docker", "image", "inspect", "--format", "{{index .RepoDigests 0}}", reference],
            capture_output=True,
            text=True,
            check=True,
            timeout=30,
        )
    except (OSError, subprocess.SubprocessError):
        return {"reference": reference, "digest": "unavailable"}
    digest = completed.stdout.strip()
    if not digest.startswith("sha256:"):
        return {"reference": reference, "digest": "unavailable"}
    return {"reference": reference, "digest": digest}


def record_provenance(client: SyncCKANClient, out: dict[str, object]) -> dict[str, object]:
    """Record stack provenance: resolved image digests and the CKAN-reported version.

    Args:
        client: A constructed sync client used only for the typed ``status_show`` read.
        out: The artifact mapping the provenance block merges into under the ``stack`` key.

    Returns:
        The same mapping after merging the provenance block.
    """
    stack: dict[str, object] = {"images": [_docker_image_digest(reference) for reference in EVIDENCE_IMAGES]}
    envelope = client.action_discovery.status_show()
    version: str | None = None
    if envelope.items and isinstance(envelope.items[0], MappingRecord):
        reported = envelope.items[0].payload.get("ckan_version")
        version = reported if isinstance(reported, str) else None
    stack["ckan_version"] = version if version is not None else "unreported"
    out["stack"] = stack
    return out


def confirmed_destructive_policy() -> MutationPolicy:
    """Return the confirmed destructive policy used for every purge dispatch."""
    return MutationPolicy(
        destructive=True,
        confirmation=ConfirmationPolicy(confirmed=True),
        concurrency=ConcurrencyPolicy(overwrite=True),
    )


def _write_artifact(path: Path, document: dict[str, object]) -> Path:
    """Write one JSON artifact and return its path."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(document, indent=2) + "\n", encoding="utf-8")
    return path


def _receipt_artifact(
    role: str, action: str, receipt: MutationReceipt, provenance: dict[str, object]
) -> dict[str, object]:
    """Assemble one capture-receipt artifact with full stack provenance."""
    return {
        "schema_version": 1,
        "kind": "capture_receipt",
        "role": role,
        "action": action,
        "receipt": receipt.to_dict(),
        "stack": provenance["stack"],
    }


def _forbidden_artifact(
    role: str, action: str, error: ForbiddenError, provenance: dict[str, object]
) -> dict[str, object]:
    """Assemble one per-tier forbidden observation artifact."""
    return {
        "schema_version": 1,
        "kind": "capture_forbidden",
        "role": role,
        "action": action,
        "operation": error.operation,
        "platform": str(error.platform),
        "capability_state": error.capability_state,
        "stack": provenance["stack"],
    }


def capture_identity_presence(client: SyncCKANClient) -> dict[str, bool]:
    """Assert the three seeded identities by presence, never by user counts."""
    presence: dict[str, bool] = {}
    for identity in IDENTITIES:
        try:
            client.users.user_show(id=identity)
        except Exception:
            presence[identity] = False
        else:
            presence[identity] = True
    return presence


def capture_sysadmin_receipts(client: SyncCKANClient, out_dir: Path, provenance: dict[str, object]) -> list[Path]:
    """Create and purge one scratch entity per purge family through typed methods."""
    policy = confirmed_destructive_policy()
    flows = (
        ("dataset_purge", SCRATCH_DATASET, client.datasets.dataset_purge),
        ("organization_purge", SCRATCH_ORG, client.organizations.organization_purge),
        ("group_purge", SCRATCH_GROUP, client.groups.group_purge),
    )
    paths: list[Path] = []
    for action, scratch, purge in flows:
        if action == "dataset_purge":
            client.datasets.package_create(name=scratch)
        elif action == "organization_purge":
            client.organizations.organization_create(name=scratch)
        else:
            client.groups.group_create(name=scratch)
        receipt = purge(id=scratch, policy=policy).receipt
        paths.append(
            _write_artifact(
                out_dir / "receipts" / f"sysadmin-{action}.json",
                _receipt_artifact("sysadmin", action, receipt, provenance),
            )
        )
    return paths


def capture_org_admin_receipts(client: SyncCKANClient, out_dir: Path, provenance: dict[str, object]) -> list[Path]:
    """Capture the org-admin tier: standard-tier successes plus a forbidden purge."""
    paths: list[Path] = []
    created = client.datasets.package_create(name=ORG_ADMIN_DATASET, owner_org=EVIDENCE_ORG)
    paths.append(
        _write_artifact(
            out_dir / "receipts" / "org_admin-package_create.json",
            _receipt_artifact("org_admin", "package_create", created.receipt, provenance),
        )
    )
    deleted = client.datasets.package_delete(id=ORG_ADMIN_DATASET)
    paths.append(
        _write_artifact(
            out_dir / "receipts" / "org_admin-package_delete.json",
            _receipt_artifact("org_admin", "package_delete", deleted.receipt, provenance),
        )
    )
    try:
        client.datasets.dataset_purge(id=ORG_ADMIN_DATASET, policy=confirmed_destructive_policy())
    except ForbiddenError as error:
        paths.append(
            _write_artifact(
                out_dir / "receipts" / "org_admin-dataset_purge-forbidden.json",
                _forbidden_artifact("org_admin", "dataset_purge", error, provenance),
            )
        )
    else:
        raise SystemExit("org-admin dataset_purge unexpectedly succeeded; tier evidence invalid")
    return paths


def capture_user_forbidden(client: SyncCKANClient, out_dir: Path, provenance: dict[str, object]) -> Path:
    """Capture the regular-user tier's forbidden administrative attempt."""
    try:
        client.organizations.organization_create(name=USER_ORG)
    except ForbiddenError as error:
        return _write_artifact(
            out_dir / "receipts" / "user-organization_create-forbidden.json",
            _forbidden_artifact("user", "organization_create", error, provenance),
        )
    raise SystemExit("regular-user organization_create unexpectedly succeeded; tier evidence invalid")


def bulk_execute_item(
    client: SyncCKANClient, policy_factory: Callable[[], MutationPolicy | None], *, mode: str = "create"
) -> Callable[[CatalogId], MutationReceipt]:
    """Map typed package_create/package_delete calls onto the bulk receipt contract.

    Args:
        client: The capture client carrying the authorization for the bulk items.
        policy_factory: Zero-argument callable producing each item's mutation policy.
        mode: ``create`` or ``delete`` — the typed method backing the adapter.

    Returns:
        A callable satisfying BulkExecutor's ``Callable[[CatalogId], MutationReceipt]``.
    """
    if mode == "create":

        def create_item(item: CatalogId) -> MutationReceipt:
            result = client.datasets.package_create(name=item.value, policy=policy_factory())
            return result.receipt

        return create_item
    if mode == "delete":

        def delete_item(item: CatalogId) -> MutationReceipt:
            result = client.datasets.package_delete(id=item.value, policy=policy_factory())
            return result.receipt

        return delete_item
    raise ValueError("Bulk adapter modes are 'create' or 'delete'.")


def _summary_document(summary: BulkSummary) -> dict[str, object]:
    """Serialize the terminal bulk aggregate without its error object."""
    return {
        "total": summary.total,
        "succeeded": summary.succeeded,
        "failed": summary.failed,
        "skipped": summary.skipped,
        "settled": summary.settled,
        "outstanding": summary.outstanding,
        "dispatches": summary.dispatches,
        "state": summary.state,
        "cancelled": summary.cancelled,
        "budget_exhausted": summary.budget_exhausted,
        "elapsed_seconds": summary.elapsed_seconds,
        "reason": summary.reason,
    }


def _run_bulk_phase(client: SyncCKANClient, items: tuple[CatalogId, ...], mode: str) -> dict[str, object]:
    """Execute one bulk phase (create or delete) and return its evidence document."""
    plan = BulkPlan(operation=BULK_OPERATION, items=items)
    checkpoints: list[dict[str, object]] = []

    def sink(checkpoint: BulkCheckpoint) -> None:
        checkpoints.append(checkpoint.to_dict())

    executor = BulkExecutor(
        bulk_execute_item(client, lambda: None, mode=mode),
        policy=BulkExecutionPolicy(max_parallelism=1),
        checkpoint_sink=sink,
    )
    started = monotonic()
    indexes: list[int] = []
    events: list[BulkItemReceipt] = []
    summary: BulkSummary | None = None
    for event in executor.stream(plan):
        if isinstance(event, BulkSummary):
            summary = event
        else:
            indexes.append(event.index)
            events.append(event)
    if summary is None:
        raise SystemExit(f"bulk {mode} run produced no terminal summary")
    if indexes != sorted(indexes) or indexes != list(range(len(items))):
        raise SystemExit(f"bulk {mode} run emitted unordered or incomplete receipts: {indexes}")
    last_receipts = checkpoints[-1].get("item_receipts") if checkpoints else None
    return {
        "mode": mode,
        "plan": plan.to_dict(),
        "item_receipt_indexes": indexes,
        "item_outcomes": [event.receipt.outcome for event in events],
        "checkpoints_recorded": len(checkpoints),
        "last_checkpoint_settled": len(last_receipts) if isinstance(last_receipts, list) else 0,
        "resumption_cursor": checkpoints[-1]["resumption_cursor"] if checkpoints else None,
        "duration_seconds": round(monotonic() - started, 3),
        "summary": _summary_document(summary),
    }


def run_bulk_capture(client: SyncCKANClient, bulk_count: int, out_dir: Path, provenance: dict[str, object]) -> Path:
    """Run the D-25 bulk create+delete flow through the runtime BulkExecutor.

    The run is single-threaded by design (max_parallelism=1); concurrent bulk
    guarantees remain declared semantics for a later phase.

    Args:
        client: The sysadmin capture client performing the mutations.
        bulk_count: Number of datasets created and then deleted.
        out_dir: Directory receiving the bulk-run artifact.
        provenance: The provenance block embedded into the artifact.

    Returns:
        The path of the written bulk-run artifact.
    """
    items = tuple(
        CatalogId(CatalogPlatform.CKAN, ResourceKind.DATASET, f"{BULK_PREFIX}-{index:03d}")
        for index in range(bulk_count)
    )
    phases = [_run_bulk_phase(client, items, mode) for mode in ("create", "delete")]
    document = {"schema_version": 1, "kind": "bulk_run_evidence", "bulk_count": bulk_count, "phases": phases}
    document.update(provenance)
    return _write_artifact(out_dir / "bulk-run.json", document)


def cleanup_scratch(client: SyncCKANClient, bulk_count: int) -> None:
    """Purge every scratch and bulk dataset the capture created, ignoring failures."""
    policy = confirmed_destructive_policy()
    targets = [ORG_ADMIN_DATASET] + [f"{BULK_PREFIX}-{index:03d}" for index in range(bulk_count)]
    for name in targets:
        try:
            client.datasets.dataset_purge(id=name, policy=policy)
        except Exception:
            continue


def main(argv: Sequence[str] | None = None) -> int:
    """Run the one-shot capture and write every artifact under the out directory."""
    parser = build_parser()
    args = parser.parse_args(argv)
    if args.bulk_count < 1:
        raise SystemExit("--bulk-count must be a positive integer")
    credentials_path = Path(args.credentials_file).expanduser()
    credentials = load_credentials(credentials_path)
    origin = recorded_origin(credentials_path)
    if origin is not None and origin.rstrip("/") != args.origin.rstrip("/"):
        raise SystemExit(f"credentials file records origin {origin!r} which does not match --origin {args.origin!r}")
    out_dir = Path(args.out_dir).expanduser().resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    provenance: dict[str, object] = {}
    receipt_paths: list[Path] = []
    with ExitStack() as stack:
        clients = {
            role: stack.enter_context(create_sync_client(build_capture_settings(args.origin, credential)))
            for role, credential in credentials.items()
        }
        record_provenance(clients["sysadmin"], provenance)
        presence = capture_identity_presence(clients["sysadmin"])
        missing = [identity for identity, present in presence.items() if not present]
        if missing:
            raise SystemExit(f"seeded identities missing from the stack: {missing}")
        receipt_paths.extend(capture_sysadmin_receipts(clients["sysadmin"], out_dir, provenance))
        receipt_paths.extend(capture_org_admin_receipts(clients["org_admin"], out_dir, provenance))
        receipt_paths.append(capture_user_forbidden(clients["user"], out_dir, provenance))
        bulk_path = run_bulk_capture(clients["sysadmin"], args.bulk_count, out_dir, provenance)
        cleanup_scratch(clients["sysadmin"], args.bulk_count)
    summary_path = _write_artifact(
        out_dir / "capture-summary.json",
        {
            "schema_version": 1,
            "kind": "capture_summary",
            "origin": args.origin,
            "identity_presence": presence,
            "receipt_files": [str(path) for path in receipt_paths],
            "bulk_run": str(bulk_path),
            **provenance,
        },
    )
    print(f"identity presence asserted for: {', '.join(presence)}")
    print(f"receipt artifacts: {len(receipt_paths)} under {out_dir / 'receipts'}")
    print(f"bulk artifact: {bulk_path}")
    print(f"capture summary: {summary_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
