"""Named, overridable defaults for runtime safety controls."""

DEFAULT_CONNECT_BUDGET_SECONDS = 10.0
DEFAULT_READ_BUDGET_SECONDS = 30.0
DEFAULT_WRITE_BUDGET_SECONDS = 30.0
DEFAULT_OPERATION_TOTAL_BUDGET_SECONDS = 60.0
DEFAULT_BREAKER_FAILURE_THRESHOLD = 5
DEFAULT_BREAKER_COOLDOWN_SECONDS = 30.0
DEFAULT_BULK_MAX_PARALLELISM = 4
